docs: Add upgrade edp 3.8 guide
epam/edp-install pull request #200
Opened 2024-04-24 06:41 UTC by Rolika4

# Pull Request Template

## Description
Please include a summary of the change and why it is needed.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [* ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

## Checklist:
- [* ] I have performed a self-review of my own code
- [* ] I have commented my code, particularly in hard-to-understand areas
- [ *] I have made corresponding changes to the documentation
- [ *] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ *] New and existing unit tests pass locally with my changes
- [ *] Pull Request contain one commit. I squash my commits

## Screenshots (if appropriate):

## Additional context
Add any other context or screenshots about the feature request here.

2024-04-24 06:53 UTC, SergK requested changes
@NikolayMarusenko please review as well

2024-04-24 06:53 UTC, SergK commented on docs/operator-guide/upgrade-edp-3.0.md
let's keep this file, we can just hide it from navigation

2024-04-24 06:53 UTC, SergK commented on docs/operator-guide/upgrade-edp-3.8.md
> +    Navigate to Keycloak realm with `Portal` client. Update `Valid redirect URIs` field:
what if we perform this configuration using keycloak-operator? let's just mention this.

2024-04-24 06:53 UTC, SergK commented on docs/operator-guide/upgrade-edp-3.8.md
> +4. Update webhooks for Github and GitLab
I thought this will be update automatically by helm chart

2024-04-24 06:53 UTC, SergK commented on docs/operator-guide/upgrade-edp-3.8.md
> +1. Remove all ArgoCD applications:
let's add warning, that this will remove existing deployments

2024-04-24 06:53 UTC, SergK commented on mkdocs.yml
> -            - v2.12 to 3.0: operator-guide/upgrade-edp-3.0.md
it's ok to remove from here, but let's keep the file

2024-04-24 12:30 UTC, Rolika4 commented on docs/operator-guide/upgrade-edp-3.8.md
> +4. Update webhooks for Github and GitLab
add use-case for command-line update

2024-04-24 12:30 UTC, Rolika4 commented on docs/operator-guide/upgrade-edp-3.8.md
> +1. Remove all ArgoCD applications:
done

2024-04-24 12:31 UTC, Rolika4 commented on docs/operator-guide/upgrade-edp-3.8.md
> +    Navigate to Keycloak realm with `Portal` client. Update `Valid redirect URIs` field:
we do not manage this resource from edp-install or add-ons repo

2024-04-24 12:31 UTC, Rolika4 commented on mkdocs.yml
> -            - v2.12 to 3.0: operator-guide/upgrade-edp-3.0.md
done

2024-04-25 13:21 UTC, NikolayMarusenko commented on docs/operator-guide/upgrade-edp-3.8.md
> +# Upgrade EDP v3.7 to 3.8
Lets use KubeRocketCI instead of EDP

2024-04-25 13:24 UTC, NikolayMarusenko commented on docs/operator-guide/upgrade-edp-3.8.md
> +
please add description that we remove CustomResourceDefinition edpcomponents.v1.edp.epam.com support and if user use CR in this CRD, before remove CRD user need to remove CR.

2024-04-25 13:25 UTC, NikolayMarusenko commented on docs/operator-guide/upgrade-edp-3.8.md
> +    kubectl -n edp delete EDPComponents sonar
maybe we can remove all CR for EDPComponents CRD?

2024-04-25 13:27 UTC, NikolayMarusenko commented on docs/operator-guide/upgrade-edp-3.8.md
> +4. Remove all ArgoCD applications:
Pleas add description why user need to remove ArgoCD applications,

2024-04-25 13:28 UTC, NikolayMarusenko commented on docs/operator-guide/upgrade-edp-3.8.md
> +            enabled: true
please fix spaces: https://github.com/epam/edp-tekton/blob/master/charts/pipelines-library/values.yaml#L364

2024-04-25 13:31 UTC, NikolayMarusenko commented on docs/operator-guide/upgrade-edp-3.8.md
> +
Please add description that this KubeRocketCI version require ArgoCD version with applicationset support and provide link to our guide with argocd RBAC hack.

2024-04-26 06:34 UTC, Rolika4 reviewed
done

2024-04-26 07:35 UTC, NikolayMarusenko commented on docs/operator-guide/upgrade-edp-3.8.md
> +This section provides detailed instructions for upgrading the EPAM Delivery Platform to version 3.8.1. Follow the steps and requirements outlined below:
KubeRocketCI

2024-04-26 07:37 UTC, NikolayMarusenko commented on docs/operator-guide/upgrade-edp-3.8.md
> +      Beginning from version 3.8.x KubeRocketCI uses Argo CD application set instead apllications to manage deploy environments, please double check that your upgrade your Argo CD instance to work wi
please provide required version of argocd with application set support

2024-05-02 16:18 UTC, NikolayMarusenko approved these changes

2024-05-02 17:08 UTC, SergK approved these changes

2024-05-02 17:08 UTC, merged