docs: Update RELEASES md file (#311)
epam/edp-install pull request #312
Opened 2024-10-04 15:57 UTC by Oleksandr123234

# Pull Request Template

## Description
This change contains updates for RELEASES.md file.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

## Checklist:
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Pull Request contains one commit. I squashed my commits

2024-10-07 14:24 UTC, NikolayMarusenko commented on RELEASES.md
> +By integrating chat assistants with the platform, users can get an intelligent assistant which can provide them with informational support.
assistant can provide any support, it depend on assistant configuration

2024-10-07 14:26 UTC, NikolayMarusenko commented on RELEASES.md
> +Now users can make up their own build, review, or deploy pipelines and easily apply them to their when both creating and editing Codebases and Environments.
'Now users can make up their own build, review, or deploy pipelines' - previously we also have this feature, this feature more about flexible and easy approach how to define pipelines and customization

2024-10-07 14:35 UTC, NikolayMarusenko commented on RELEASES.md
> +Apart from that, we introduce a new pipeline type called "clean". This pipeline is launched when clicking the new "Clean" button within Environments and performs [customizable application deletion](h
It is not about pipeline, it is about flow of deletion.

2024-10-07 14:36 UTC, NikolayMarusenko commented on RELEASES.md
> +It is also worth mentioning that we are continuously working on widening the platform capabilities, this time we announce that KubeRocketCI is now capable of deploying RPM packages in addition to tra
'traditional' - rephrase please

2024-10-07 15:10 UTC, MykolaMarusenko commented on RELEASES.md
> +* C and C++ language support with Make and CMake build tools has been added to the platform. ([#335](https://github.com/epam/edp-headlamp/issues/335))
duplicate with line 107

2024-10-07 15:11 UTC, NikolayMarusenko commented on RELEASES.md
> +* A new tab called "Variables" has been added to the Environment (formerly Stage) page. In this tab, users can set key-value variables to put into the application as environment variables. ([#404](ht
this is major feature, lets highlight in top of doc

2024-10-07 15:11 UTC, MykolaMarusenko commented on RELEASES.md
> +* Add codebase codemie integration ([#323](https://github.com/epam/edp-headlamp/issues/323))
duplicate with line 110

2024-10-07 15:12 UTC, NikolayMarusenko commented on RELEASES.md
> +## Version 3.10.0 <a name="3.10.0"></a> (October 8, 2024)
we have major feature with autodeploy, please provide details for this case

2024-10-07 15:13 UTC, NikolayMarusenko commented on RELEASES.md
> +These release notes start with introducing Bitbucket Git server support. This feature enriches the users' toolset and makes the platform more attractive for Bitbucket users.
please rephrase that we support new VCS provider

2024-10-11 06:29 UTC, SergK requested changes

2024-10-11 06:29 UTC, SergK commented on RELEASES.md
> +We have added a new deployment trigger type called "[Auto-stable](https://github.com/epam/edp-cd-pipeline-operator/blob/master/deploy-templates/crds/v2.edp.epam.com_stages.yaml#L161)" has been added
deployment strategy

2024-10-11 06:29 UTC, SergK commented on RELEASES.md
> +Deploy pipelines now support manual approval. When creating a custom deploy pipeline, users can include a checkpoint to prompt for approval or rejection before proceeding to the next step.
Deployment pipelines have been enhanced with a manual approval feature. This allows developers to integrate a checkpoint within their custom deployment pipelines, requiring a manual review and approval process before the pipeline can advance to the next stage. This ensures greater control and oversight over the deployment process.

2024-10-11 06:29 UTC, SergK commented on RELEASES.md
> +Users can now deliver their applications in the form of RPM packages, implemented using Ansible. Correspondingly, support for C and C++ languages with make and CMake build tools has been added to the
let's split this and:

Users can now automate the deployment of their applications packaged as RPMs, utilizing Ansible for this process.

2024-10-11 06:29 UTC, SergK commented on RELEASES.md
> +We have added a new deployment trigger type called "[Auto-stable](https://github.com/epam/edp-cd-pipeline-operator/blob/master/deploy-templates/crds/v2.edp.epam.com_stages.yaml#L161)" has been added
original: where intermediate pipelines are skipped

smth like: where intermediate versions are skipped and the latest versions are deployed

2024-10-11 09:43 UTC, SergK commented on RELEASES.md
> +Our platform now integrates with Large Language Models, such as ChatGPT, as an intelligent [chat assistant](https://docs.kuberocketci.io/docs/next/user-guide/add-ai-assistant). Depending on your spec
`Depending on your specified settings`

Depending on your assistant's settings

2024-10-11 09:46 UTC, SergK commented on RELEASES.md
> +We are expanding the options for managing applications. Users are now able to automate the deployment of their applications packaged as RPMs, utilizing Ansible for this process.
`We are expanding the options for managing applications.`

We are expanding the options for delivering applications.

2024-10-11 09:50 UTC, SergK commented on RELEASES.md
> +Additionally, we have added new functionality to our deployment pipelines. A new tab called Variables has been added to the Environment (formerly Stage) details page. In this tab, users can specify k
This release adds new functionality to deployment pipelines. A new tab, "Variables," has been added to the Environment details page (previously known as the Stage details page). In this tab, users can specify key-value pairs that will be injected into the deployment pipeline as environment variables. This enhancement allows users to configure application deployment settings directly within the KubeRocketCI portal, providing greater flexibility and control over the deployment process.

2024-10-11 09:53 UTC, SergK commented on RELEASES.md
> +Deployment pipelines have been enhanced with a manual approval feature. This allows developers to integrate a checkpoint within their custom deployment pipelines, requiring a manual review and approv
We are pleased to introduce a new Manual Approval feature on the platform. This feature allows developers to incorporate an approval task within their custom deployment pipelines, requiring a manual review and approval before advancing to the next stage. While deployment pipelines are a primary use case for this capability, the approval task can also be leveraged in other workflows. This enhancement provides greater control and oversight, ensuring all processes meet required standards and criteria before progressing.

2024-10-11 11:56 UTC, SergK commented on RELEASES.md
> +We have added the ability to specify custom build and review pipelines with just one click when editing or creating new codebase branches. This enhancement increases flexibility when working with cod
let's remove 'with just one click'

2024-10-21 12:19 UTC, SergK approved these changes

2024-10-21 12:19 UTC, merged